// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQhEP8yLwQFF2UKb0qkzOepPbcmwUVwQ',
    appId: '1:802883275734:web:d833937309e6a317b8b277',
    messagingSenderId: '802883275734',
    projectId: 'mobile-5c919',
    authDomain: 'mobile-5c919.firebaseapp.com',
    databaseURL: 'https://mobile-5c919-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-5c919.firebasestorage.app',
    measurementId: 'G-8514CD4HNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1bVnSr2xAIOBLfoGafOBFK4hPP8DqX4',
    appId: '1:802883275734:android:8b1a40ab004207c6b8b277',
    messagingSenderId: '802883275734',
    projectId: 'mobile-5c919',
    databaseURL: 'https://mobile-5c919-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-5c919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1FQgNszhft3AjLQOpFoF4HH_lhKI5lRU',
    appId: '1:802883275734:ios:346a3da5e29ed42db8b277',
    messagingSenderId: '802883275734',
    projectId: 'mobile-5c919',
    databaseURL: 'https://mobile-5c919-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-5c919.firebasestorage.app',
    iosClientId: '802883275734-bo809tmmb4pumni5v8k4pmrjlq47h8h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1FQgNszhft3AjLQOpFoF4HH_lhKI5lRU',
    appId: '1:802883275734:ios:346a3da5e29ed42db8b277',
    messagingSenderId: '802883275734',
    projectId: 'mobile-5c919',
    databaseURL: 'https://mobile-5c919-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-5c919.firebasestorage.app',
    iosClientId: '802883275734-bo809tmmb4pumni5v8k4pmrjlq47h8h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQhEP8yLwQFF2UKb0qkzOepPbcmwUVwQ',
    appId: '1:802883275734:web:3219c2cc59dd04c9b8b277',
    messagingSenderId: '802883275734',
    projectId: 'mobile-5c919',
    authDomain: 'mobile-5c919.firebaseapp.com',
    databaseURL: 'https://mobile-5c919-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-5c919.firebasestorage.app',
    measurementId: 'G-W1DDBK5SY9',
  );
}
